language: java

after_script: echo $Foo

script: 
  - cd sdk ; mvn test
  - echo $test1
  - echo $testproj
  
jdk:
  - oraclejdk7
  #- openjdk7
  - oraclejdk8

env:
 global:
   - Foo=bar
   - test1=aa
 matrix:
   - secure: L20To/+xg6JAeUeyhS4iPXZj8yqciH08UEJbzuraAWUWgEAZ9Sd4sf9VBfzv3BB855NthIWXnAVJ2iPM355n4B5cbIwxPFLI9ajMkbq7MkuTIgJ9hRmT45unbRRja5jl2aF4e3qremUxeLT2uYqqrZQV00Fv+UJko3kCn6eDl5jWFynhUXnTef3IOqfmIChiJVTRuDj1PfxGsh7j4INzHkl3dEcbh5X5WLJkjiVBns+RdjQu13nMKGLZ4O5eAoczDVHyMkJ52274pqexbYYuOnSn7+zY7pSYq41w3GTJsPYVcGJ7UFx9tZQA0UGJDYI+5c6G/eyjPpm9Oka0kMxgzA== 
   #- secure: GOQIILb2NGGBdPhoZbTV/mjuAojwmLy98OgYZ0t/vppmthlK8xOS6j/xgxwOGBFjCToW1HHd+EKArPnqwVNRiVNizgUA6b3w79ZOY3nppJxQHadXiA3mmuo1gNvP1Vmdm09MaWtBegcTjz4hAtPJuks5GooxZynEhJHIOQFCg/Xoy521Pox9kmUdYNwOmYxkgxqy4oHC/Jr/6rXbPMNrUIeCNe1v/4N30O1WXWgTGdxzbAlLlRZxXXpSq3iO0TrRxZjuf2vp0A686jjxoEt1uOlTYExvLbq5ov3ykQ/3PoDG3lwdTvV00crEpP29dY+xShBgYXXL4tuDp1ecgqdUOg== 
   - DOCKER_COMPOSE_VERSION="1.5.0rc3"
  
matrix:
  include:
    - jdk: openjdk7
      env: testproj=name
  exclude:
    - jdk: oraclejdk8
      env: DOCKER_COMPOSE_VERSION="1.5.0rc3"
  
before_script: echo $DOCKER_COMPOSE_VERSION and $final
      

#cache: true
