language: java
script: 
  - cd sdk ; mvn test
  - echo $test
  
jdk:
  - oraclejdk7
  - openjdk7
  - oraclejdk8

env:
  matrix:
    #- FOO=bar  
    - BAR=foo
  global:
    - secure: esLv52+lPwNKtJz0Kwdk4tPWz3JGkhVafYXTwUa2Y0nRAwLxejG50WFQ2of3i5B0KHbnklyWn4xumti7DSQg7lk5XelE+qtMANH35SQ4kHgcp7KxEiCN63g7HrvIT6yP0lMuxgO4Efjtlo1aI0wHO5o/Z1BJOSImk/BzepGcgk5D8/2b2drFjJKqauyc8j9kFBqtsD2m9zOAr7zS1HL9D0/T9buQMOot0BwD34KpIYVNBrX/334YVNCwZstVMwYJ9doHBEkgCTkuBxTr8Cb8BIpH/t+Astwv4Pl0a9OrzPT3K6rJJSwSh8/R/cM+ucEYyKYPeUBJvKZOoh/tvLaM1Q==
    - secure: hCC82FJGXanM1tBP3RFOLqZ0GEJ1Zyv3M7zXaRG/b79wwTptEM31ObxvJYbwAuD2e9Wytl7r+DZ+v0hYvZNyUwCtr8GPDVJqPJJ1Vmt7qVZ3S2izxolHmy+HIV7vElAXxn2aCcD3RnQT0OHVbz8OQ17h3a9NFfCQwRkIchHXZHl85ddhXPc+vsNPKvUhLg9iAR22z27wcpeG6i26/I9yzkKshjyb9fMcgvxOcIwPL7aUOn5bCNPx25wAakQLyd5hQohczcY3c91mzoI8

matrix:
  exclude:
    - jdk: openjdk7
    - env: FOO=bar

cache: true
