language: java

script: 
  - cd sdk ; mvn test
  - echo $test
  
jdk:
  - oraclejdk7
  - openjdk7
  - oraclejdk8

env:
  matrix:
    - Foo=testing  
  global:
    - secure: cdyh5oLbFo+Cl59JP3IsEP5Z8DY8qWrC5wtdYSQiYXlzwuhJ29jeaiZzXeTEGhmZVvXxuMW92YaGVygAeN9//jKq/yitrcOZi0qrSA4DJlywUTWOBzfb0s+xYTehuKx7PDWPA1NkvBS+g+Z4hbstMIje+ET7oA/tqfGr7gOjZlKGukG+5lsepAzL8U1rs+E9ynGxnrNxemd2DL2lFsbo8Y/Fhp5ovYQH/P4SnEZ+oABgWmf7aTvaeplkUCLak+Lb9iS1piZ23824hlKrxlCsGxlE3JbyubzaodIahiA6MrSwg38RaCjk9fTNAUSYQ/VG1AxvfZQK1xWm6N/XTQDbrQ==
   
matrix:
  exclude:
    - jdk: openjdk7
      env: test=name

#cache: true
