language: java


script: 
  - cd sdk ; mvn test
  - echo $test
  
jdk:
  - oraclejdk7
  #- openjdk7
  - oraclejdk8

env:
  - test=name
  
matrix:
  include:
    - jdk: openjdk7
      #env: test=name
    
  exclude:
    - jdk: oraclejdk7
      

#cache: true
